name: build-site

on:
  push:
    branches: [master]
  # merge:
  #   branches: [master]


jobs:
  redeploy_site:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Build
        run: |
          system('mkdir -p docs')
          install.packages("bookdown")
          install.packages("downlit")
          install.packages("xml2")
          bookdown::render_book("index.Rmd", quiet = TRUE, output_dir = 'docs')
        shell: Rscript {0}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs

