name: learn-github-actions-params

on: workflow_dispatch

jobs:
  find-github-actions-params:
    runs-on: ubuntu-latest
    steps:
      - name: "GitHub events"
        run: |
          echo '${{ toJSON(github.event) }}' | jq
        shell: bash
