name: check-available

on: workflow_dispatch

jobs:
  basic-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "read gh actions event info"
        run: |
          echo '${{ toJSON(github.event) }}' | jq
        shell: bash
