name: learn-github-actions-params

on: workflow_dispatch

jobs:
  find-github-actions-params:
    runs-on: ubuntu-latest
    steps:
      - name: "GitHub events"
        run: |
          echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: "Save GH events to file"
        run: |
          echo '${{ toJSON(github.event) }}' | jq | cat > gh_events.json
      - name: "Check file exists"
        run: |
          ls

