name: github-permissions

on:
  workflow_dispatch:


jobs:
  test-permissions:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: make a file
        run: |
          echo "Hello it is" `date` >> new_file.txt
          
      - name: set git credentials to gh actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - name: commit file
        run: |
          git add -A
          git commit -m "Add text to new_file.txt"

      - name: push file
        run: |
          git push
  
