name: just-learning

on: workflow_dispatch

jobs:
  use_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create new branch
        run: |
          git checkout -b testing_branch
      - name: push new branch
        run: |
          git push --set-upstream testing_branch origin/testing_branch
