name: just-learning

on: workflow_dispatch

jobs:
  use_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create new branch
      # Ok so, create the desired branch first and push it to the remote.
      # Then you can fetch and switch to it.
        run: |
          git fetch
          git switch testing_branch

      - name: add content
      # The action doesn't seem to approve of not declaring user info?
        run: |
          echo "hello world">>sometext.txt
          git add -A
          git commit -m "some text lol"
      - name: push new branch
      # note that git push --set-upstream origin XXX will only work when
      # pushing a branch to remote the first time, but fails thereafter so
      # create branch on remote first and just use git push on the action
        run: |
          git push
