name: just-learning

on: workflow_dispatch

jobs:
  use_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check contents
        run: |
          ls -a
      # - name: push new branch
      #   run: |
      #     git push --set-upstream testing_branch origin/testing_branch
