name: just-learning

on: workflow_dispatch

jobs:
  use_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create new branch
        run: |
          git checkout -b testing_branch
      - name: add content
        run: |
          [[-f sometext.txt]] | touch sometext.txt
          echo "hello world">sometext.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "some text lol"
      - name: push new branch
        run: |
          git push --set-upstream origin testing_branch
